/**
 * Typed-data scheme parity with the wallet. canonical.json's schemeVectors
 * and schemeSigningVectors are generated by the wallet
 * (myqrlwallet-frontend src/utils/signing/__tests__/generateSchemeFixtures.test.ts)
 * and checked there against an independent reference implementation. The
 * SDK must select the same scheme, reproduce every hash and digest, and
 * verify the wallet's signatures.
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { isQrlSignedTypedDataResult } from '../../types.js';
import {
  bytesToHex,
  computeTypedDataDigest,
  encodeType,
  hashStruct,
  typeHash,
  typedDataSchemeVersion,
  verifyTypedDataForSigner,
  verifyTypedDataSignature,
  type TypedDataPayload,
  type TypedDataSchemeVersion,
} from '../index.js';

interface SchemeVector {
  label: string;
  schemeVersion: TypedDataSchemeVersion;
  payload: TypedDataPayload;
  encodeTypeString: string;
  typeHashHex: string;
  domainHashHex: string;
  messageHashHex: string;
  digestHex: string;
}

interface SchemeSigningVector {
  label: string;
  hexSeed: string;
  payload: TypedDataPayload;
  schemeVersion: TypedDataSchemeVersion;
  signature: string;
  publicKey: string;
  descriptor: string;
  signer: string;
  digest: string;
}

const here = dirname(fileURLToPath(import.meta.url));
const canonical = JSON.parse(
  readFileSync(join(here, '..', '__fixtures__', 'canonical.json'), 'utf-8')
) as { schemeVectors: SchemeVector[]; schemeSigningVectors: SchemeSigningVector[] };

describe('typed-data scheme parity with the wallet', () => {
  it.each(canonical.schemeVectors.map((v) => [v.label, v] as const))(
    '%s: scheme, hashes and digest match',
    (_label, v) => {
      const { payload, schemeVersion } = v;
      expect(typedDataSchemeVersion(payload)).toBe(schemeVersion);
      expect(encodeType(payload.primaryType, payload.types)).toBe(v.encodeTypeString);
      expect(bytesToHex(typeHash(payload.primaryType, payload.types))).toBe(v.typeHashHex);
      expect(
        bytesToHex(hashStruct('QRLDomain', payload.domain, payload.types, schemeVersion))
      ).toBe(v.domainHashHex);
      expect(
        bytesToHex(hashStruct(payload.primaryType, payload.message, payload.types, schemeVersion))
      ).toBe(v.messageHashHex);
      expect(bytesToHex(computeTypedDataDigest(payload))).toBe(v.digestHex);
    }
  );

  it.each(canonical.schemeSigningVectors.map((v) => [v.label, v] as const))(
    '%s: the wallet response passes the wire check and both verifiers',
    (_label, v) => {
      expect(bytesToHex(computeTypedDataDigest(v.payload))).toBe(v.digest);
      const response = {
        signature: v.signature,
        publicKey: v.publicKey,
        descriptor: v.descriptor,
        signer: v.signer,
        digest: v.digest,
        schemeVersion: v.schemeVersion,
        domain: v.payload.domain,
      };
      expect(isQrlSignedTypedDataResult(response)).toBe(true);
      expect(verifyTypedDataSignature({ ...response, payload: v.payload })).toBe(true);
      expect(
        verifyTypedDataForSigner({ ...response, expectedSigner: v.signer, payload: v.payload })
      ).toBe(true);
    }
  );

  it('rejects a response that claims the other scheme', () => {
    for (const v of canonical.schemeSigningVectors) {
      const other =
        v.schemeVersion === 'QRL-SIGN-TYPED-v2' ? 'QRL-SIGN-TYPED-v1' : 'QRL-SIGN-TYPED-v2';
      expect(
        verifyTypedDataForSigner({
          expectedSigner: v.signer,
          descriptor: v.descriptor,
          signature: v.signature,
          publicKey: v.publicKey,
          payload: v.payload,
          schemeVersion: other,
        })
      ).toBe(false);
    }
  });

  it('a v2 signature fails once the signed payload changes', () => {
    const v2 = canonical.schemeSigningVectors.find((v) => v.schemeVersion === 'QRL-SIGN-TYPED-v2')!;
    const altered = structuredClone(v2.payload);
    (altered.message as Record<string, unknown>).nonce = '8';
    expect(
      verifyTypedDataSignature({
        signature: v2.signature,
        publicKey: v2.publicKey,
        payload: altered,
      })
    ).toBe(false);
  });
});
